#+title: TP de Calcul Numérique
#+author: Nicolas BOUTON
#+date: 2020

* Exercice 1

  Developpement limité : 
  
  \begin{equation*}
  \begin{split}
  T(x_i + h) & = T(x_i) + h \left(\frac{\delta T}{\delta x} \right)_i + h^2 \left(\frac{\delta^2 T}{\delta x^2} \right)_i + O(h^2) \\
  T(x_i - h) & = T(x_i) - h \left(\frac{\delta T}{\delta x} \right)_i + h^2 \left(\frac{\delta^2 T}{\delta x^2} \right)_i + O(h^2)
  \end{split}
  \end{equation*}

  On somme et on inverse le signe :

  \begin{equation*}
  \begin{split}
  - T(x_i + h) + 2 T(x_i) - T(x_i - h) = - h^2 \left(\frac{\delta^2 T}{\delta x^2} \right)_i + O(h^2) \\
  \frac{- T(x_i + h) + 2 T(x_i) - T(x_i - h)}{h^2} = - \left(\frac{\delta^2 T}{\delta x^2} \right)_i
  \end{split}
  \end{equation*}

  Or on a :

  \begin{equation*}
  - k \left( \frac{\delta^2 T}{\delta x^2} \right)_i = g_i, k > 0
  \end{equation*}

  On se permet de négligé k car c'est une constante dans nos prochain calcul :

  \begin{equation*}
  \begin{split}
  - T(x_i + h) + 2 T(x_i) - T(x_i - h) = h^2 g_i
  \end{split}
  \end{equation*}

  On écrit le système d'équation : 

  \begin{equation*}
  \begin{array}{ll}
  u_0 = T_0 & i = 0 \\
  - u_0 + 2 u_1 - u_2 = h^2 g_1 & i = 1\\
  ... & ... \\
  - u_{k-1} + 2 u_k - u_{k+1} = h^2 g_k & i = k\\
  ... & ... \\
  - u_{n-1} + 2 u_n - u_{n+1} = h^2 g_n & i = n\\
  u_n = T_n & i = n + 1 \\
  \end{array}
  \end{equation*}

  Avec les conditions aux bords on obtient :

  \begin{equation*}
  2 u_1 - u_2 = h^2 g_1 + T_0 \\
  - u_{n-1} + 2 u_n = h^2 g_n + T_n \\
  \end{equation*}

  Donc on explicite le système linéaire $Au = g$ :

  \begin{equation*}
  A = \left[
  \begin{array}{ccccccc}
  2 & -1 & 0 & - & - & - & 0 \\
  -1 & 2 & -1 & . &  &  & |  \\
  0 & -1 & . & . & . &  & |  \\
  | & . & . & . & . & . & |  \\
  | & & . & . & . & -1 & 0  \\
  | & & & . & -1 & 2 & -1  \\
  0 & - & - & - & 0 & -1 & 2 \\
  \end{array}
  \right]
  \end{equation*}

  \begin{equation*}
  u = \left[
  \begin{array}{c}
  T_1 \\
  | \\
  T_n \\
  \end{array}
  \right]
  \end{equation*}

  \begin{equation*}
  g = \left[
  \begin{array}{c}
  h^2 T_1 + T_0 \\
  h^2 T_2 \\
  | \\
  h^2 T_{n-1} \\
  h^2T_n + T_1\\
  \end{array}
  \right]
  \end{equation*}

  Comme il n'y a pas de source de chaleur, on a \forall i \in [ 1, n
  ] : h^2 g_i = 0

  D'où g = \left[
  \begin{array}{c}
  T_0 \\
  0 \\
  | \\
  0 \\
  T_1 \\
  \end{array}
  \right]
 
  Et la solution qnalytique qui se déguage est : 

  $$ T(x) = T_0 + x (T_1 - T_0) $$

* Exercice 2
** Arch  
*** Bibliothèque

    Pour l'intallation des bibliothèque *cblas* et *lapacke* :
    #+begin_src
    $ sudo pacman -S cblas lapacke
    #+end_src

*** Makefile

    Il faut modifier la ligne qui link les librairie en linkant la
    bibliothèque *cblas*:
    
    #+begin_src c
    #
    # -- librairies
    LIBS=-llapacke -lcblas -lm
    #+end_src

* Exercice 3
** Question 1

   Les matrices pour utiliser *BLAS* et *LAPACK* en *C* sont allouées
   et déclarées de la même manière que les tableaux en *C*. Mais elles
   doivent être stockées dans l'un des formats suivant :

   - stockage conventionnel en 2 dimension (ex: int tab[10][10])
   - stockage compact pour les matrices symétrique, hermitienne et
     triangulaire (stockage dans un tableau à 1 dimension des éléments
     de la matrice supérieur ou inférieur)
   - stockage bandes pour les matrices à bandes (cad que les
     diagonales autour de la diagonale principale contiennent la
     plupart des NNZ) (GB et GE)
   - utilisation de 2 ou 3 tableaux à 1 dimension pour stocker les
     matrices bidiagonale et tridiagonale respectivement

   source : http://performance.netlib.org/lapack/lug/node121

** Question 2

- Les constantes \(LAPACK\_ROW\_MAJOR\) et \(LAPACK\_COL\_MAJOR\)
  signifie la priorité ligne ou colonne respectivement de la
  représentation de la matrice.
- Effectivement, cet argument sert si on utilise un stockage
  particulier en *1 dimension* car il faut préciser si on a utilisé
  une priorité ligne ou colonne pour stocker la matrice.

** Question 3
   
   La *leading dimension* permet de savoir qu'elle élément correspond
   à la prochaine colonne ou la prochaine ligne suivant le stockage
   colonne ou ligne respectivement.

   - Si on choisis un stockage priorité ligne, alors la *leading
     dimension* correspond au nombre d'élément d'une ligne pour
     pouvoir accéder à la ligne suivante.
   - Si on choisis un stockage priorité colonne, alors la *leading
     dimension* correspond au nombre d'élément d'une colonne pour
     pouvoir accéder à la colonne suivante.

** Question 4
*** Résumé

   La fonction \(LAPACKE\_dgbsv\) permet de calculer le résultat d'un
   système linéaire du type $A * X = B$, avec *X* l'inconnu, *A* une
   matrice et *B* le second membre, où *X* et *B* peuvent être des
   vecteurs ou des matrices.

*** Argument

   Elle prend en argument la dimension de la matrice, le nombre du
   sous-diagonnale ainsi que de sur-diagonnale.

*** Implémentation

   Cette fonction implémente une décomposition *LU* à pivot partiel et
   la méthode de dessente et de remonté.

*** Sources

    http://www.math.utah.edu/software/lapack/lapack-d/dgbsv.html
   
** Question 5
* Annexe

  Dépôt : https://github.com/Sholde/CN/tree/master/partie_2/poisson

